from langsmith import traceable, get_current_run_tree
from langchain_core.messages import SystemMessage, convert_to_openai_messages
from pydantic import BaseModel, Field
import instructor
from langchain_core.messages import SystemMessage, convert_to_openai_messages

from jinja2 import Template
from langchain_openai import ChatOpenAI
import instructor
from api.agents.utils.prompt_management import prompt_template_config
from api.agents.tools import get_formatted_item_context


### Q&A Agent Response Model
class RAGUsedContext(BaseModel):
    id: str = Field(description="ID of item used to answer the question")
    description: str = Field(description="Description of item used to answer the question")

class FinalResponse(BaseModel):
    answer: str = Field(description="The final answer to the user's query, generated by the model after tool usage.")
    references: list[RAGUsedContext] = Field(description="A list of items from the retrieved context that were used to generate the final answer, including their IDs and descriptions.")

### Intent Router response model
class IntentRouterResponse(BaseModel):
    question_relevant: bool = Field(description="Whether the user's question is relevant to the products in the database")
    answer: str = Field(description="A brief explanation of why the question is relevant or not.")

traceable(
    name="agent_node",
    run_type="llm",
    metadata={
        "ls_provider": "openai",
        "ls_model_name": "gpt-5.4-mini",
    }
)
def agent_node(state) -> dict: # agent node always gets state object
    # jinja template for the prompt that we will send to the llm
    # teh agent needs to see what has been done ...
    template = prompt_template_config("api/agents/prompts/qna_agent.yaml", "qna_agent")
    prompt = template.render() ## render the template with the query from the
    llm = ChatOpenAI(
        model="gpt-5.4-mini", 
        reasoning_effort = "low",
        use_responses_api = True # we cannot use completions api ... (indicates augmented llm) 
    )

    # tools can be functions or pydantic models
    llm_with_tools = llm.bind_tools(
        [get_formatted_item_context, FinalResponse], # we can also return a final response from the model instead of going through the graph again (this is useful for when we want to return a final answer to the user instead of going through the graph again)
        tool_choice="any" # auto means llm can suggest or not suggest the tool (any forces the llm to suggest any of the tools provided in the toolset)
    )

    response = llm_with_tools.invoke([
        SystemMessage(content=prompt), ## open ais abstractioon on creating a message object from a string (llm only takes in messages objects as input so we need to convert our prompt into a message object),
        *state.messages ## we also want to pass in the message history so that the model can see what has been done in previous iterations
    ])
    
    current_run  = get_current_run_tree()
    if current_run: # of tokens used for input and how many used for output
        current_run.metadata["usage_metadata"] = {
            "input_tokens": response.usage_metadata["input_tokens"],
            "output_tokens": response.usage_metadata["output_tokens"],
            "total_tokens": response.usage_metadata["total_tokens"],
        }
    
    final_answer = False
    answer = ""
    references = []
    
    if(len(response.tool_calls) > 0):
        for tool_call in response.tool_calls:
            if tool_call.get("name") == "FinalResponse":
                final_answer = True
                references.extend(tool_call.get("args").get("references"))
                answer = tool_call.get("args").get("answer")
                
    # response.tool_calls.... 
    return {
        "messages": [response], # appended with new response
        "final_answer": final_answer,
        "iteration": state.iteration + 1,
        "answer": answer,
        "references": references
    }
    
@traceable(
    name="route_intent", 
    run_type = 'llm',
    metadata={
        "ls_provider": "openai",
        "ls_model_name": "gpt-5.4-mini",
    }
)
def intent_router_node(state) -> dict:
    template = prompt_template_config("api/agents/prompts/intent_router_agent.yaml", "intent_router_agent")
    prompt = template.render()
    messages = state.messages
    conversation = []
    for message in messages:
        conversation.append(convert_to_openai_messages(message))

    client = instructor.from_provider(
        "openai/gpt-5.4-nano",
        mode=instructor.Mode.RESPONSES_TOOLS
    )
    
    response, raw_response = client.create_with_completion(
        messages=[
            {"role": "system", "content": prompt},
            *conversation
        ],
        reasoning={"effort": "none"},
        response_model = IntentRouterResponse
    )
    
    current_run  = get_current_run_tree()
    if current_run: # of tokens used for input and how many used for output
        current_run.metadata["usage_metadata"] = {
            "input_tokens": raw_response.usage.input_tokens,
            "output_tokens": raw_response.usage.output_tokens,
            "total_tokens": raw_response.usage.total_tokens,
        }
    
    print("Intent Router Response:", response)
    
    return {
        "question_relevant": response.question_relevant, # pydantic class
        "answer": response.answer
    }
    