from langsmith import traceable, get_current_run_tree
from langchain_core.messages import AIMessage, SystemMessage, convert_to_openai_messages
from pydantic import BaseModel, Field
import instructor
from langchain_core.messages import SystemMessage, convert_to_openai_messages

from jinja2 import Template
from langchain_openai import ChatOpenAI
import instructor
from api.agents.utils.prompt_management import prompt_template_config
from api.agents.utils.utils import postprocess_response
from api.agents.tools import get_formatted_item_context, get_formatted_reviews_context, add_to_shopping_cart, remove_from_cart, get_shopping_cart, reserve_warehouse_items, check_warehouse_availability

### Q&A Agent Response Model
class RAGUsedContext(BaseModel):
    id: str = Field(description="ID of item used to answer the question")
    description: str = Field(description="Description of item used to answer the question")

class FinalQnAAgentResponse(BaseModel):
    """Call this tool when the final answer is possible using available context"""
    answer: str = Field(description="The final answer to the user's query, generated by the model after tool usage.")
    references: list[RAGUsedContext] = Field(description="A list of items from the retrieved context that were used to generate the final answer, including their IDs and descriptions.")


### General Agent Response 
class FinalAgentResponse(BaseModel):
    answer: str = Field(description="Answer to the question")
    
### coordinator agent response
class Plan(BaseModel):
    next_agent: str = Field(description="The next agent to invoke, either 'product_qna_agent', 'shopping_cart_agent', or 'warehouse_manager_agent'")


### Product QNA agent
traceable(
    name="product_qna_agent",
    run_type="llm",
    metadata={
        "ls_provider": "openai",
        "ls_model_name": "gpt-5.4-mini",
    }
)
def product_qna_agent(state) -> dict: # agent node always gets state object
    # jinja template for the prompt that we will send to the llm
    # teh agent needs to see what has been done ...
    template = prompt_template_config("api/agents/prompts/qna_agent.yaml", "qna_agent")
    prompt = template.render()
    
    llm = ChatOpenAI(
        model="gpt-5.4-mini", 
        reasoning_effort = "low",
        use_responses_api = True # we cannot use completions api ... (indicates augmented llm) 
    )

    # tools can be functions or pydantic models
    llm_with_tools = llm.bind_tools(
        [get_formatted_reviews_context, get_formatted_item_context, FinalQnAAgentResponse], # we can also return a final response from the model instead of going through the graph again (this is useful for when we want to return a final answer to the user instead of going through the graph again)
        tool_choice="any" # auto means llm can suggest or not suggest the tool (any forces the llm to suggest any of the tools provided in the toolset)
    )

    response = llm_with_tools.invoke([
        SystemMessage(content=prompt), ## open ais abstractioon on creating a message object from a string (llm only takes in messages objects as input so we need to convert our prompt into a message object),
        *state.messages ## we also want to pass in the message history so that the model can see what has been done in previous iterations
    ])
    
    current_run  = get_current_run_tree()
    if current_run: # of tokens used for input and how many used for output
        current_run.metadata["usage_metadata"] = {
            "input_tokens": response.usage_metadata["input_tokens"],
            "output_tokens": response.usage_metadata["output_tokens"],
            "total_tokens": response.usage_metadata["total_tokens"],
        }
    
    postprocessed_response = postprocess_response(response, "FinalQnAAgentResponse", agent_name="product_qna_agent")
    final_answer = postprocessed_response.get("final_answer")
    answer = postprocessed_response.get("answer")
    references = postprocessed_response.get("references")
    response = postprocessed_response.get("response")
                
    # response.tool_calls.... 
    return {
            "messages": [response], # appended with new response
            "product_qna_agent":{
                "final_answer": final_answer,
                "iteration": state.product_qna_agent.iteration + 1,
            },
            "answer": answer,
            "references": references
    }
    
### shopping cart agent node
traceable(
    name="shopping_cart_agent",
    run_type="llm",
    metadata={
        "ls_provider": "openai",
        "ls_model_name": "gpt-5.4-mini",
    }
)
def shopping_cart_agent(state) -> dict: # agent node always gets state object
    template = prompt_template_config("api/agents/prompts/shopping_cart_agent.yaml", "shopping_cart_agent")
    prompt = template.render(user_id=state.user_id, cart_id=state.cart_id)
    llm = ChatOpenAI(
        model="gpt-5.4-mini", 
        reasoning_effort = "low",
        use_responses_api = True
    )

    llm_with_tools = llm.bind_tools(
        [get_shopping_cart, remove_from_cart, add_to_shopping_cart, FinalAgentResponse],
        tool_choice="any"
    )

    response = llm_with_tools.invoke([
        SystemMessage(content=prompt),
        *state.messages
    ])
    current_run  = get_current_run_tree()
    if current_run: # of tokens used for input and how many used for output
        current_run.metadata["usage_metadata"] = {
            "input_tokens": response.usage_metadata["input_tokens"],
            "output_tokens": response.usage_metadata["output_tokens"],
            "total_tokens": response.usage_metadata["total_tokens"],
        }
    
    postprocessed_response = postprocess_response(response, "FinalAgentResponse", agent_name="shopping_cart_agent")
    final_answer = postprocessed_response.get("final_answer")
    answer = postprocessed_response.get("answer")
    response = postprocessed_response.get("response")
                
    return {
            "messages": [response],
            "shopping_cart_agent": {
                "final_answer": final_answer,
                "iteration": state.shopping_cart_agent.iteration + 1,
            },
            "answer": answer,
    }


traceable(
    name="warehouse_manager_agent",
    run_type="llm",
    metadata={
        "ls_provider": "openai",
        "ls_model_name": "gpt-5.4-mini",
    }
)
def warehouse_manager_agent(state) -> dict: # agent node always gets state object
    # jinja template for the prompt that we will send to the llm
    # teh agent needs to see what has been done ...
    template = prompt_template_config("api/agents/prompts/warehouse_manager_agent.yaml", "warehouse_manager_agent")
    prompt = template.render()
    llm = ChatOpenAI(
        model="gpt-5.4-mini", 
        reasoning_effort = "low",
        use_responses_api = True # we cannot use completions api ... (indicates augmented llm) 
    )

    # tools can be functions or pydantic models
    llm_with_tools = llm.bind_tools(
        [check_warehouse_availability, reserve_warehouse_items, FinalAgentResponse], # we can also return a final response from the model instead of going through the graph again (this is useful for when we want to return a final answer to the user instead of going through the graph again)
        tool_choice="any" # auto means llm can suggest or not suggest the tool (any forces the llm to suggest any of the tools provided in the toolset)
    )

    response = llm_with_tools.invoke([
        SystemMessage(content=prompt), ## open ais abstractioon on creating a message object from a string (llm only takes in messages objects as input so we need to convert our prompt into a message object),
        *state.messages ## we also want to pass in the message history so that the model can see what has been done in previous iterations
    ])
    current_run  = get_current_run_tree()
    if current_run: # of tokens used for input and how many used for output
        current_run.metadata["usage_metadata"] = {
            "input_tokens": response.usage_metadata["input_tokens"],
            "output_tokens": response.usage_metadata["output_tokens"],
            "total_tokens": response.usage_metadata["total_tokens"],
        }
    
    postprocessed_response = postprocess_response(response, "FinalAgentResponse", agent_name="warehouse_manager_agent")
    final_answer = postprocessed_response.get("final_answer")
    answer = postprocessed_response.get("answer")
    response = postprocessed_response.get("response")
                
    # response.tool_calls.... 
    return {
            "messages": [response], # appended with new response
            "warehouse_manager_agent": {
                "final_answer": final_answer,
                "iteration": state.warehouse_manager_agent.iteration + 1,
            },
            "answer": answer,
    }
    
    
## coordinator agent
traceable(
    name="coordinator_agent",
    run_type="llm",
    metadata={
        "ls_provider": "openai",
        "ls_model_name": "gpt-5.4-mini",
    }
)
def coordinator_agent(state) -> dict: # agent node always gets state object
    template = prompt_template_config("api/agents/prompts/coordinator_agent.yaml", "coordinator_agent")
    prompt = template.render()
    llm = ChatOpenAI(
        model="gpt-5.4-mini", 
        reasoning_effort = "medium",
        use_responses_api = True
    )

    llm_with_tools = llm.bind_tools(
        [FinalAgentResponse, Plan],
        tool_choice="required"
    )

    response = llm_with_tools.invoke([
        SystemMessage(content=prompt),
        *state.messages
    ])
    current_run  = get_current_run_tree()
    if current_run: # of tokens used for input and how many used for output
        current_run.metadata["usage_metadata"] = {
            "input_tokens": response.usage_metadata["input_tokens"],
            "output_tokens": response.usage_metadata["output_tokens"],
            "total_tokens": response.usage_metadata["total_tokens"],
        }
    trace_id = str(current_run.trace_id) if current_run else ""
    
    final_answer = False
    answer = ""
    next_agent = ""
    
    if len(response.tool_calls) > 0:
        if response.tool_calls[0].get("name") == "Plan":
            next_agent = response.tool_calls[0].get("args").get("next_agent")
            response = AIMessage(content=f"[Coordinator Agent Decision]: {next_agent}")
        else:
            post_processed_response = postprocess_response(response, "FinalAgentResponse")
            final_answer = post_processed_response.get("final_answer")
            answer = post_processed_response.get("answer")
            response = post_processed_response.get("response")


    return { 
        "messages": [response] if response is not None else [],
        "coordinator_agent": {
            "iteration": state.coordinator_agent.iteration + 1,
            "final_answer": final_answer,
            "next_agent": next_agent
        },
        "answer": answer,
        "trace_id": trace_id
    }
